.TH SZYFROWANIE 1 "MAJ 2025" "v0.3" "Manual uzytkownika"
.SH NAZWA
szyfrowanie \- graficzny program do szyfrowania i deszyfrowania plikow

.SH SKLADNIA
.B szyfrowanie.sh
[OPCJE]

.SH OPIS
Program umozliwia szyfrowanie i deszyfrowanie plikow, katalogow i grup plikow z uzyciem openssl.
Uzywa narzedzia graficznego Zenity do interakcji z uzytkownikiem.

.SH OPCJE
.TP
.B \-h, \-\-help
Wyswietla pomoc
.TP
.B \-v, \-\-version
Wyswietla wersje

.SH AUTOR
Autor: Bartosz Pacyga

.SH WERSJA
0.3

.SH ZOBACZ TAKZE
openssl(1), zenity(1)
